spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: ${RDS_HOST:jdbc:mysql://localhost:3306/poc1}    
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:password}
    hikari:
      connection-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 20
      max-lifetime: 600000   
  jpa:
    open-in-view: false    
  sql:
    init:
      platform: org.hibernate.dialect.MYSQL8Dialect
 
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
            
